### ISSUE TITLE
Bukkit Addons not showing up

### ISSUE THREAD

**Issue by Dmitchell94** [webbukkit/DynmapCBBridge#3]
DynmapForge V 2.3
Dynmap-GriefPrevention 0.70
Dynmap-WorldGuard 0.80
DynmapCBBridge 2.3

Forge 1614
Thermos

none of the layers from the bukkit plugins are showing up on dynmap:

http://play.theblackmage.net:8123/

**Comment by Dmitchell94** [comment]
change the port and it works :|

**Comment by mikeprimm** [comment]
If you are on a hosted server, sometimes you will be sharing an IP address, and the port will already be taken by another server running dynmap :) .   Basically, the best advice is that if you are on a hosted server AND your MC server port number is not 'default' (25565), it's probably a good idea to assign Dynmap to a non-default port too.
